version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - "db"
    environment:
      DATABASE_URL: postgres://postgres@db/postgres
    command: ["bash", "wait-for-postgres-then-run.sh"]
